// All possible button colors
var buttonColours = ["red", "blue", "green", "yellow"];

// Stores the sequence generated by the game
var gamePattern = [];

// Stores the sequence clicked by the user
var userClickedPattern = [];

// Tracks if the game has started
var started = false;

// Tracks the current level
var level = 0;


// -------------------------------------
// PLAY SOUND FUNCTION
// -------------------------------------
function playSound(name) {
  // Plays the sound file matching the color or "wrong"
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}


// -------------------------------------
// BUTTON PRESS ANIMATION
// -------------------------------------
function animatePress(currentColour) {
  $("#" + currentColour).addClass("pressed");

  setTimeout(function () {
    $("#" + currentColour).removeClass("pressed");
  }, 100);
}


// -------------------------------------
// GAME START (FIRST KEY PRESS)
// -------------------------------------
$(document).keypress(function () {
  if (!started) {
    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});


// -------------------------------------
// GENERATE NEXT GAME SEQUENCE
// -------------------------------------
function nextSequence() {

  // Reset user pattern for the new level
  userClickedPattern = [];

  // Increase level
  level++;

  // Update heading
  $("#level-title").text("Level " + level);

  // Pick a random color
  var randomNumber = Math.floor(Math.random() * 4);
  var randomChosenColour = buttonColours[randomNumber];

  // Add color to game pattern
  gamePattern.push(randomChosenColour);

  // Flash and play sound
  $("#" + randomChosenColour).fadeOut(100).fadeIn(100);
  playSound(randomChosenColour);

  console.log("Game Pattern:", gamePattern);
}


// -------------------------------------
// USER BUTTON CLICKS
// -------------------------------------
$(".btn").click(function () {

  var userChosenColour = $(this).attr("id");

  // Save user's click
  userClickedPattern.push(userChosenColour);

  playSound(userChosenColour);
  animatePress(userChosenColour);

  // Check user's latest answer
  checkAnswer(userClickedPattern.length - 1);
});


// -------------------------------------
// CHECK USER'S ANSWER
// -------------------------------------
function checkAnswer(currentLevel) {

  // Compare user's latest answer with game pattern
  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) {

    // If user has completed the full pattern
    if (userClickedPattern.length === gamePattern.length) {
      setTimeout(function () {
        nextSequence();
      }, 1000);
    }

  } else {

    // ❌ USER GOT IT WRONG

    // Play wrong sound
    playSound("wrong");

    // Flash red background
    $("body").addClass("game-over");

    // Remove red flash after 200ms
    setTimeout(function () {
      $("body").removeClass("game-over");
    }, 200);

    // Update title
    $("#level-title").text("Game Over, Press Any Key to Restart");

    // Reset the game
    startOver();
  }
}


// -------------------------------------
// RESET GAME
// -------------------------------------
function startOver() {
  level = 0;          // Reset level
  gamePattern = [];  // Clear game memory
  started = false;   // Allow restart on key press
}
